### ISSUE TITLE
zlib: incorrect header check

### ISSUE THREAD

**Issue by filfat** [filfat/pocket-minecraft-protocol#1]
Perhaps it's not a byte array anyways..

Thoughts @mhsjlw?

**Comment by mhsjlw** [comment]
Where does this occur and what version of the game. I need some more details :worried:

**Comment by filfat** [comment]
This occurs with the new 91 protocol added in 0.16. It occurs when trying to inflate the response from game_login with zlib to be able to decrypt it.

**Comment by mhsjlw** [comment]
It's possible they've made changes. Take a look at Genisys. I haven't been following the 0.16 update.

**Comment by filfat** [comment]
So, the length of the stream is supposed to be a varint.
